#define rc 3
#define box_size 12
#define half_box 6
#define particles_count 128
#define total_it 5000
#define dt 0.0002
#define Temperature 1.3
#define initial_dist_by_one_axis 1.5
#define initial_dist_to_edge 2