#define rc 3
#define box_size 10
#define half_box 5
#define particles_count 32
#define total_it 5000
#define dt 0.0002
#define Temperature 1.3
#define initial_dist_by_one_axis 2
#define initial_dist_to_edge 2