#define rc 3
#define box_size 8
#define half_box 4
#define particles_count 64
#define nmax 8000
#define total_it 16000
#define Temperature 1.3
#define initial_dist_by_one_axis 1.2
#define initial_dist_to_edge 2